apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.10.1
    releaseName: kcp-glbc
    namespace: cert-manager
    valuesInline:
      installCRDs: true
      global:
        leaderElection:
          namespace: cert-manager
      extraArgs: ["--controllers=*,-ingress-shim"]