---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIBinding
metadata:
  name: cert-manager
spec:
  reference:
    workspace:
      path: root:users:ev:vo:system-apiserver:kcp-glbc
      exportName: cert-manager-stable
