apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: glbc
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - services
  - secrets
  verbs:
  - "*"
- apiGroups:
  - "networking.k8s.io"
  resources:
  - ingresses
  - ingresses/status
  verbs:
  - "*"
- apiGroups:
  - "kuadrant.dev"
  resources:
  - "*"
  verbs:
  - "*"

