apiVersion: scheduling.kcp.dev/v1alpha1
kind: Placement
metadata:
  name: default
spec:
  locationResource:
    group: workload.kcp.dev
    resource: synctargets
    version: v1alpha1
  locationSelectors:
    - {}
  locationWorkspace: root:default:kcp-glbc-user-compute
  namespaceSelector: {}