---
apiVersion: v1
kind: Service
metadata:
  name: glbc-webhooks
spec:
  ports:
    - name: http-port
      port: 8443
      targetPort: http-port
      protocol: TCP
  selector:
    app.kubernetes.io/name: kcp-glbc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-glbc
spec:
  rules:
    - host: host.whatever.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glbc-webhooks
                port:
                  number: 8443
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "test.example.com"
webhooks:
- name: "test.example.com"
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    url: "https://host.whatever.com:8443/validate"
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5                  